[package]
name = "slint_minesweeper"
version = "0.1.0"
edition = "2021"
build = "build.rs"
rust-version = "1.80.0"

[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

[lints.clippy]
# https://github.com/rust-lang/rust-clippy
implicit_return = "deny"
needless_return = "allow"

[dependencies]
slint = "1.12"
rand = "0.8.5"
web-time = "1.1.0" # https://github.com/rust-lang/rust/issues/48564

[build-dependencies]
slint-build = "1.8.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
getrandom = { version = "0.2.2", features = ["js"] }
web-sys = { version = "0.3.72", features = ["Window", "Location", "console"] }

[target.'cfg(target_os = "android")'.dependencies.slint]
version = "1.12"
features = ["backend-android-activity-06"]

[package.metadata.android]
package = "dev.marvinscham.minesweeper"
label   = "Minesweeper"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version    = 26
target_sdk_version = 34
